runtime: python39

handlers:
  - url: /css
    static_dir: app.css

  - url: /img/(.*\.(gif|png|jpg|jpeg))
    static_files: logo-mkk-nav
    upload: images/(.*\.(gif|png|jpg))

  - url: /img/(.*\.(gif|png|jpg|jpeg))
    static_files: logo-mkk
    upload: images/(.*\.(gif|png|jpg|jpeg))

  - url: /img/(.*\.(gif|png|jpg|jpeg))
    static_files: logo-web
    upload: images/(.*\.(gif|png|jpg))

  - url: /.*
    script: index.html
